import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./component/layout/Footer";
import TopHeader from "./component/layout/TopHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div className="flex flex-col min-h-screen">
        {/* ✅ Add TopHeader at the top */}
        <TopHeader />
        
        {/* ✅ Main Content Area */}
        <main className="flex-grow">{children}</main>
  
        {/* ✅ Footer at the bottom */}
        <Footer />
      </div>
    </body>
  </html>
  
  );
}
